In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text':['people watch movie','movie watch movie','people write comment','movie write comment'],'output':[1,1,0,0]})

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
#cv = CountVectorizer(2,2) unigram(people watch...)
#cv = CountVectorizer(1,2) both unigram or bigram(people...,people watch..)
#cv = CountVectorizer(3,3) trigram ( people wath movie..)

In [4]:
bow = cv.fit_transform(df['text'])

In [5]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'movie': 1, 'write': 4, 'comment': 0}


In [6]:
print(bow[0].toarray())
print(bow[1].toarray())


[[0 1 1 1 0]]
[[0 2 0 1 0]]


In [7]:
cv.transform(["movie watch and write comment of movie"]).toarray()

array([[1, 2, 0, 1, 1]])